version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Etc/UTC
       ports:
            - 5055:5055
       volumes:
            - /home/opc/Docker/jellyseerr/config:/app/config
       restart: unless-stopped
       labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyseerr.rule=Host(`XXX.XXXX.XX`)" # your sub-domain where bazarr will be hosted for exemple jellyseer.mysite.com
            - "traefik.http.routers.jellyseerr.entrypoints=websecure"
            - "traefik.http.routers.jellyseerr.tls.certresolver=lets-encrypt"
       networks:
            - web

networks:
  web:
    external: true
