---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/opc/Docker/Bazarr/config:/config
      - /media/movies:/movies #optional
      - /media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`XXXX.XXXX.XX`)" # your sub-domain where bazarr will be hosted for exemple bazarr.mysite.com
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls.certresolver=lets-encrypt"
    networks:
      - web

networks:
  web:
    external: true
